### ISSUE TITLE
Views on Svelte vs React 🤔!!

### ISSUE THREAD

**Issue by gkanishk** [tanaypratap/ama#274] opened 2020-04-26 07:40 UTC
"Sir is it still safe to go on learning react? How come this svelte thing just hyped up suddenly? Is it really better than react? Tanay"

- Asked on TeamTanay telegram group by **Prajval**

**Comment by tanaypratap** [comment] 2020-04-30 19:23
Duplicate of #275 
Closing this one. 
Thank you for opening this ticket on quick notice.

**Closed as completed** 2020-04-30 19:23 UTC
